### ISSUE TITLE
Guess Who Server funktioniert nicht

### ISSUE THREAD

**Issue by FaserF** [discordler/discordler.github.io#1]
"Der Server läuft nicht."

LOG:
ERROR!: Can't create physics object for models/props/de_tides/patio_chair2.mdl
Error! Flag "$halflambert" is multiply defined in material "models/props_construction/light_floodlight01_on"!
Nav File is wrong or something (4)
Initializing Steam libraries for secure Internet server
[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
No account token specified; logging into anonymous game server account.  (Use sv_setsteamaccount to 
Connection to Steam servers successful.
Public IP is 178.26.133.119.
Assigned anonymous gameserver Steam ID [A-1:2827363330(8162)].
VAC secure mode is activated.

**Comment by Bilalui** [comment]
- Workshop collection entfernt
- Guesswho addon von github bezogen
- Workshop collection für Maps eingefügt
- Server erfolgreich gestartet und getestet
