### ISSUE TITLE
CoD Modern Warfare 3 Server

### ISSUE THREAD

**Issue by FaserF** [discordler/discordler.github.io#10]

**Comment by FaserF** [comment]
Warte auf Status der Windows VM.

Mw3 Server benötigt Windows und läuft nicht auf Linux. Siehe Ticket #12

**Comment by FaserF** [comment]
Tekno MW3 custom Server wenn möglich

http://nevy.enjin.com/forum/m/34323142/viewthread/28089237-installing-tekno-mw3-dlc-tutorial/post/107121383

**Comment by Bilalui** [comment]
Abgelehnt. Durch Tekno oder auch "AlterIWNet" genannt wird das Originalspiel gecrackt. Dadurch ist ein VAC geschützter Server ned möglich. Nach meinen Wissen wurde Tekno vor 5 Jahren eingestellt

**Comment by FaserF** [comment]
https://www.itsmods.com/forum/Thread-Release-Votemap-plugin.html

-insecure +set dedicated 2 +set sv_config "server.cfg" +set net_ip 0.0.0.0 +set net_queryPort 28015 +set net_port 28016 +set net_authPort 8766 +set net_masterServerPort 28017 +start_map_rotate

Status Update MW3 Server: Windows Server 2016 VM läuft, sollte bald verfügbar sein!

**Comment by FaserF** [comment]
MW3 Server ist online siehe https://discordler.github.io/mw3
