### ISSUE TITLE
NAT VM not working. troubleshooting

### ISSUE THREAD

**Issue by Bilalui** [discordler/discordler.github.io#12]

**Comment by Bilalui** [comment]
Virtualisierungstechnik "qemu" ruft die libvirt hooks in /etc/libvirt/hooks/hooks.json nicht auf
Neuinstallation zwecklos

**Comment by FaserF** [comment]
Windows Server 2016 installiert in VM auf Linux.
Funktioniert.
Remote Desktop auch möglich
