### ISSUE TITLE
OGP Update

### ISSUE THREAD

**Issue by FaserF** [discordler/discordler.github.io#17]
OGP Update kann nicht installiert werden:

![image](https://user-images.githubusercontent.com/12374134/39589518-b86d7780-4efe-11e8-9218-6198a0b0080c.png)

**Comment by Bilalui** [comment]
Der Ordner /var/www/HTML/ogp muss mit chown -r www-data:www-data bearbeitet werden

**Comment by FaserF** [comment]
Danke @Bilalui er hat es gefixt
